export const municipalitiesAraEsp = [
  "Alcalá d’o Bispe",
  "Almudébar",
  "Banastars",
  "Casbas de Uesca",
  "Uesca",
  "Lobarre",
  "Os Corrals",
  "Morillo de Galligo",
  "Sietemo",
  "Santolaria de Galligo",
  "Bizién",
  "L’Aínsa-Sobrarbe",
  "A Fueba",
  "Chistén",
  "A Buerda",
  "O Pueyo d’Araguás",
  "San Chuan de Plan",
  "Benás",
  "Castilló de Sos",
  "Billanoba",
  "Santa Zilia",
  "Lo Grau"
]

export const municipalitiesEspAra = [
  "Alcalá del Obispo",
  "Almudévar",
  "Banastas",
  "Casbas de Huesca",
  "Huesca",
  "Loarre",
  "Loscorrales",
  "Murillo de Gállego",
  "Siétamo",
  "Santa Eulalia de Gállego",
  "Vicién",
  "Aínsa-Sobrarbe",
  "La Fueva",
  "Gistaín",
  "Labuerda",
  "El Pueyo de Araguás",
  "San Juan de Plan",
  "Benasque",
  "Castejón de Sos",
  "Villanova",
  "Santa Cilia",
  "El Grado"
]
