export const municipalitiesCatEsp = [
  "Areny de Noguera",
  "Benavarri",
  "Estopanyá",
  "Laspaúls",
  "Monesma i Caixigar",
  "Montanui",
  "Pont de Montanyana",
  "Tolba",
  "Viacamp i Lliterà",
  "El Campell",
  "El Torricó",
  "Valdellou",
  "Castellonroi",
  "Tamarit de Llitera",
  "Vensilló",
  "Mequinensa",
  "Torrent de Cinca",
  "Villella de Cinca",
  "Saidí",
  "Favara",
  "Faió",
  "Nonasp",
  "Aiguaviva de Bergantes",
  " Bellmunt de Mesquí",
  "La Canyada de Beric",
  "La Codonyera",
  "La Ginebrosa",
  "Torre de Vilella",
  "Arenys de Lledó",
  "Beseit",
  "Calaceit",
  "Queretes",
  "Fórnols",
  "La Freixneda",
  "Fontdespatla",
  "Massalió",
  "Montroig",
  "Pena-roja de Tastavins",
  "Ráfels",
  "Torredarques",
  "La Torre del Comte",
  "La Vall del Tormo",
  "Vall de Roures",
  "Valljunquera"
]

export const municipalitiesEspCat = [
  "Arén",
  "Benabarre",
  "Estopiñán del Castillo",
  "Laspaúles",
  "Monesma y Cajigar",
  "Montanuy",
  "Puente de Montañana",
  "Tolva",
  "Viacamp y Litera",
  "Alcampell",
  "Altorricón",
  "Baldellou",
  "Castillonroy",
  "Tamarite de Litera",
  "Vencillón",
  "Mequinenza",
  "Torrente de Cinca",
  "Velilla de Cinca",
  "Zaidín",
  "Fabara",
  "Fayón",
  "Nonaspe",
  "Aguaviva",
  "Belmonte de San José",
  "La Cañada de Verich",
  "La Codoñera",
  "La Ginebrosa",
  "Torrevelilla",
  "Arens de Lledó",
  "Beceite",
  "Calaceite",
  "Cretas",
  "Fórnoles",
  "La Fresneda",
  "Fuentespalda",
  "Mazaleón",
  "Monroyo",
  "Peñarroya de Tastavins",
  "Ráfales",
  "Torre de Arcas",
  "Torre del Compte",
  "Valdeltormo",
  "Valderrobres",
  "Valjunquera"
]
